### PR TITLE
just a syntax fix

### PR DESCRIPTION
**Pull request by benoitzohar**
also, removed unnecessary use of "Js".

### CODE REVIEW

**Comment by jihdeh** [comment]
You suggest we take this away? but it is a JS framework.

**Comment by benoitzohar** [comment]
Yes it is but the name is just "Aurelia".
Also, "AngularJS" 1 becomes "Angular" 2, and many more in your list, I didn't want to fix it all though, before I got your approbation.

**Comment by jihdeh** [comment]
Okay acceptable, but i think it's better off if we leave it as it is, so people do know it's a `JS` thing. :)

**Comment by benoitzohar** [comment]
Ok, I restored the "Js" suffix and still fixed the syntax error in "Auriela".

**Comment by jihdeh** [comment]
👍

**Pull request merged**
